export const BLOCK_CREATE = 'BLOCK_CREATE';
export const BLOCK_SAVE = 'BLOCK_SAVE';
export const BLOCK_CLONE = 'BLOCK_CLONE';
export const BLOCK_MERGE = 'BLOCK_MERGE';
export const BLOCK_DELETE = 'BLOCK_DELETE';
export const BLOCK_RENAME = 'BLOCK_RENAME';
export const BLOCK_SET_COLOR = 'BLOCK_SET_COLOR';
export const BLOCK_SET_SBOL = 'BLOCK_SET_SBOL';
export const BLOCK_SET_SEQUENCE = 'BLOCK_SET_SEQUENCE';
export const BLOCK_COMPONENT_ADD = 'BLOCK_COMPONENT_ADD';
export const BLOCK_COMPONENT_MOVE = 'BLOCK_COMPONENT_MOVE';
export const BLOCK_COMPONENT_REMOVE = 'BLOCK_COMPONENT_REMOVE';
export const BLOCK_ANNOTATE = 'BLOCK_ANNOTATE';
export const BLOCK_REMOVE_ANNOTATION = 'BLOCK_REMOVE_ANNOTATION';

export const INSPECTOR_TOGGLE_VISIBILITY = 'INSPECTOR_TOGGLE_VISIBILITY';

export const INVENTORY_SEARCH = 'INVENTORY_SEARCH';
export const INVENTORY_TOGGLE_VISIBILITY = 'INVENTORY_TOGGLE_VISIBILITY';

export const PROJECT_CREATE = 'PROJECT_CREATE';
export const PROJECT_SAVE = 'PROJECT_SAVE';
export const PROJECT_MERGE = 'PROJECT_MERGE';
export const PROJECT_RENAME = 'PROJECT_RENAME';
export const PROJECT_ADD_CONSTRUCT = 'PROJECT_ADD_CONSTRUCT';

export const UI_ADD_CURRENT = 'UI_ADD_CURRENT';
export const UI_SET_CURRENT = 'UI_SET_CURRENT';
export const UI_TOGGLE_CURRENT = 'UI_TOGGLE_CURRENT';
export const UI_TOGGLE_DETAIL_VIEW = 'UI_TOGGLE_DETAIL_VIEW';

export const UI_SET_CURRENT_CONSTRUCT = 'UI_SET_CURRENT_CONSTRUCT';
