export const BLOCK_CREATE = 'BLOCK_CREATE';
export const BLOCK_STASH = 'BLOCK_STASH';
export const BLOCK_SAVE = 'BLOCK_SAVE';
export const BLOCK_LOAD = 'BLOCK_LOAD';
export const BLOCK_CLONE = 'BLOCK_CLONE';
export const BLOCK_MERGE = 'BLOCK_MERGE';
export const BLOCK_DELETE = 'BLOCK_DELETE';
export const BLOCK_RENAME = 'BLOCK_RENAME';
export const BLOCK_SET_COLOR = 'BLOCK_SET_COLOR';
export const BLOCK_SET_SBOL = 'BLOCK_SET_SBOL';
export const BLOCK_SET_SEQUENCE = 'BLOCK_SET_SEQUENCE';
export const BLOCK_COMPONENT_ADD = 'BLOCK_COMPONENT_ADD';
export const BLOCK_COMPONENT_MOVE = 'BLOCK_COMPONENT_MOVE';
export const BLOCK_COMPONENT_REMOVE = 'BLOCK_COMPONENT_REMOVE';
export const BLOCK_ANNOTATE = 'BLOCK_ANNOTATE';
export const BLOCK_REMOVE_ANNOTATION = 'BLOCK_REMOVE_ANNOTATION';

export const INSPECTOR_TOGGLE_VISIBILITY = 'INSPECTOR_TOGGLE_VISIBILITY';
export const INSPECTOR_FORCE_BLOCKS = 'INSPECTOR_FORCE_BLOCKS';

export const INVENTORY_SEARCH = 'INVENTORY_SEARCH';
export const INVENTORY_TOGGLE_VISIBILITY = 'INVENTORY_TOGGLE_VISIBILITY';

export const FOCUS_FORCE_PROJECT = 'FOCUS_FORCE_PROJECT';
export const FOCUS_FORCE_BLOCKS = 'FOCUS_FORCE_BLOCKS';
export const FOCUS_PROJECT = 'FOCUS_PROJECT';
export const FOCUS_CONSTRUCT = 'FOCUS_CONSTRUCT';
export const FOCUS_BLOCKS = 'FOCUS_BLOCKS';

export const PROJECT_LIST = 'PROJECT_LIST';
export const PROJECT_CREATE = 'PROJECT_CREATE';
export const PROJECT_SAVE = 'PROJECT_SAVE';
export const PROJECT_SNAPSHOT = 'PROJECT_SNAPSHOT';
export const PROJECT_LOAD = 'PROJECT_LOAD';
export const PROJECT_MERGE = 'PROJECT_MERGE';
export const PROJECT_RENAME = 'PROJECT_RENAME';
export const PROJECT_ADD_CONSTRUCT = 'PROJECT_ADD_CONSTRUCT';

export const UI_TOGGLE_DETAIL_VIEW = 'UI_TOGGLE_DETAIL_VIEW';
export const UI_SHOW_MAIN_MENU = 'UI_SHOW_MAIN_MENU';
export const UI_SHOW_USER_WIDGET = 'UI_SHOW_USER_WIDGET';
export const UI_SHOW_AUTHENTICATION_FORM = 'UI_SHOW_AUTHENTICATION_FORM';
export const UI_SHOW_DNAIMPORT = 'UI_SHOW_DNAIMPORT';
export const UI_SHOW_ABOUT = 'UI_SHOW_ABOUT';
export const UI_SET_GRUNT = 'UI_SET_GRUNT';
export const UI_SHOW_GENBANK_IMPORT = 'UI_SHOW_GENBANK_IMPORT';

export const USER_SET_USER = 'USER_SET_USER';
export const USER_LOGIN = 'USER_LOGIN';

export const CLIPBOARD_SET_DATA = 'CLIPBOARD-SET-DATA';
